--CREATE DATABASE CRUD_TEMPLATE
--DROP DATABASE CRUD_TEMPLATE

USE CRUD_TEMPLATE

CREATE TABLE CATEGORIA
(
	ID_CATEGORIA INT IDENTITY(1,1) NOT NULL,
	NOME_CATEGORIA CHAR(50)

	PRIMARY KEY (ID_CATEGORIA)
)

CREATE TABLE PRODUTO
(
	ID_PRODUTO INT IDENTITY(1,1) NOT NULL,
	NOME_PRODUTO CHAR(50),
	ID_CATEGORIA INT,
	QTDE_PRODUTO INT

	PRIMARY KEY (ID_PRODUTO),
	FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA
)

CREATE TABLE ORDEM
(
	ID_ORDEM INT IDENTITY(1,1) NOT NULL,
	ID_PRODUTO INT,
	TIPO_ORDEM CHAR(1),
	DATA_ORDEM DATETIME,
	QTDE_ORDEM INT

	PRIMARY KEY (ID_ORDEM),
	FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO
)